name: CI
permissions: read-all
env:
  GO_VERSION: "1.25"
  SQLC_VERSION: "1.30.0"
on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: make install
        run: make install

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6
          args: --timeout=5m

  sqlc-vet:
    name: sqlc vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: make install
        run: make install

      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: ${{ env.SQLC_VERSION }}

      - name: Run sqlc vet
        run: sqlc vet

  sqlc-diff:
    name: sqlc diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: make install
        run: make install

      - name: Setup sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: ${{ env.SQLC_VERSION }}

      - name: Run sqlc diff
        run: sqlc diff

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: make install
        run: make install

      - name: Run Tests with Coverage
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Print Coverage
        run: go tool cover -func=coverage.txt
